bot.token=${TELEGRAM_BOT_TOKEN}
bot.username=${TELEGRAM_BOT_USERNAME}

llm.api.url=${LLM_API_URL}
llm.system.prompt=${LLM_SYSTEM_PROMPT}
llm.model=${LLM_MODEL}
llm.api.keys=${LLM_API_KEYS}
llm.injection.prompt=${LLM_INJECTION_PROMPT}